config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'tasks#index'
  resources :tasks
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  before_update :admin_cannot_update
  before_destroy :admin_cannot_delete
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 5 }
  
  private

  def admin_cannot_update
    throw :abort if User.where(admin: true).count == 1 && self.admin_change == [true, false]
  end

  def admin_cannot_delete
    throw :abort if User.where(admin: true).count == 1 && self.admin == true
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i(show edit update destroy)
  before_action :ensure_user
  skip_before_action :login_already

  def index
    @users = User.all.includes(:tasks)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザーを作成しました"
    else
      render :new
    end
  end

  def show
    @tasks = @user.tasks
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザーを編集しました"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザーを削除しました"
    else  
      redirect_to admin_users_path
    end
  end

  private

  def ensure_user
    @users = current_user
    redirect_to tasks_path, notice: "管理者以外はアクセスできません" if @users.admin == false
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation, :admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[ new create]
  skip_before_action :login_already, only: %i[ show]
  before_action :ensure_user, only: %i[ show ]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else 
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = current_user.tasks
  end

  private

  def ensure_user
    @users = current_user
    @user = User.find(params[:id]) 
    redirect_to tasks_path if @user.id != @users.id && @users.admin == false   
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<%= form_with(model: [:admin, @user], local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :admin %>
  <%= f.select :admin, [['あり', 'true'],['なし', 'false']], { include_blank: '選択してください', selected: 0 } %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "ユーザー登録" %>
<% end %>

app/views/admin/users/edit.html.erb
<h1>編集</h1>

<%= render 'form', user: @user %>

<%= link_to 'ユーザーの一覧へ', admin_user_path %> |
<%= link_to '一覧へ戻る', admin_user_path %>

app/views/admin/users/index.html.erb
<%= link_to 'ユーザー作成', new_admin_user_path %>

<h1>管理画面</h1>

<table>

  <body>
    <thead>
      <tr>
        <th>ユーザー</th>
        <th>メールアドレス</th>
        <th>タスク登録数</th>
        <th>管理者</th>
      </tr>
    </thead>

    <tbody>
      <% @users.preload(:tasks).all.each do |user| %>
        <tr class="task_row" >
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.tasks.size %></td>
          <td><%= user.admin %></td>
          <td><%= link_to '詳細', admin_user_path(user.id), class: "btn btn-outline-primary" %></td>
          <td><%= link_to '編集', edit_admin_user_path(user.id), class: "btn btn-outline-success" %></td>
          <td><%= link_to '削除', admin_user_path(user.id), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</table>

app/views/admin/users/new.html.erb
<h1>新規ユーザー登録</h1>

<%= render 'form', task: @user %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<h1>タスク一覧</h1>

<%= form_with url: tasks_path, method: :get, scope: :task, local: true do |form| %>
    <%= form.label :タスク名検索 %>
    <%= form.text_field :title %>
    <%= form.label :状況 %>
    <%= form.select :status, Task.statuses.keys.map, include_blank: true %>
    <%= form.submit "検索" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>タスク名</th>
      <th>タスク詳細</th>
      <th scope = "col" ><%= link_to '終了期限', tasks_path(sort_deadline: "true") %></th>
      <th>状況</th>
      <th scope = "col" ><%= link_to '優先度', tasks_path(sort_priority: "true") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr class="task_row" >
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= link_to '詳細', task, class: "btn btn-outline-primary" %></td>
        <td><%= link_to '編集', edit_task_path(task), class: "btn btn-outline-success" %></td>
        <td><%= link_to '削除', task, method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>